version: '3.8'

services:
  app:
    image: 389798/link-image
    env_file:
      - .env
    container_name: link-container
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - ./src/link
    networks:
      - link-network

  mongodb:
    image: mongo
    container_name: mongo-link-container
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - link-network

networks:
  link-network:
    driver: bridge
